const batch = require('../build/lib/runtime')
const jobop = batch.BatchRuntime.getJobOperator()

batch.BatchRuntime.initEventHub()
batch.BatchRuntime.initRepository({ jobs: { datastore: 'nedb' }, jobInsts: { datastore: 'nedb' } })
	.then(() => { return jobop.loadJob('/Users/gizak/Workspace/batch/test/job1.js') })
	.then((jid) => { return jobop.newJobInstance(jid) })
	.then(()=>{ jobop._dumpRuntimeDS()})
	.then(() => { return jobop.lsJobs() })
	.then(data => { return data[0] })
	.then((jid) => { return jobop.getJob(jid) })
	.then((j)=>{ return jobop.newJobInstance(j.id)})
	.then(ji => { jobop.startJobInst(ji.id)})
	.catch(err => { console.error(err) })
