const batch = require('../build/lib/runtime')
const jobop = batch.BatchRuntime.getJobOperator()

batch.BatchRuntime.initRepository({ jobs: { datastore: 'nedb' } })
	.then(() => { return jobop.loadJob('/Users/gizak/Workspace/batch/test/job1.js') })
	.then(() => { return jobop.lsJobs() })
	.then(data => { console.log(data) })
	.then(() => { return jobop.getJob('testjob') })
	.then(data => { console.log(data) })
	.catch(err => { console.error(err) })
